import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import bcrypt from "bcryptjs";

const DATA_DIR = process.env.DATA_DIR || "/data";
const CRED_FILE = path.join(DATA_DIR, ".credentials");
const COOKIE_FILE = path.join(DATA_DIR, ".cookie");

interface DashboardCredentials {
  dashboardPasswordHash: string;
  dashboardPassword: string;
  jwtSecret: string;
  claimed?: boolean;
}

let cached: DashboardCredentials | null = null;

function generateRandom(length: number): string {
  return crypto.randomBytes(length).toString("base64url").slice(0, length);
}

function ensureCredentials(): DashboardCredentials {
  if (cached) return cached;

  // If .credentials already exists, use it
  try {
    const raw = fs.readFileSync(CRED_FILE, "utf8");
    const creds = JSON.parse(raw) as DashboardCredentials;
    // If the hash is empty (generated by entrypoint.sh), compute it now
    if (!creds.dashboardPasswordHash && creds.dashboardPassword) {
      creds.dashboardPasswordHash = bcrypt.hashSync(creds.dashboardPassword, 10);
      fs.writeFileSync(CRED_FILE, JSON.stringify(creds, null, 2), { mode: 0o600 });
    }
    cached = creds;
    return creds;
  } catch {
    // No .credentials yet — backend generates (fallback if entrypoint didn't run)
  }

  const dashboardPassword = generateRandom(16);
  const jwtSecret = generateRandom(64);
  const dashboardPasswordHash = bcrypt.hashSync(dashboardPassword, 10);

  const creds: DashboardCredentials = { dashboardPasswordHash, dashboardPassword, jwtSecret };
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(CRED_FILE, JSON.stringify(creds, null, 2), { mode: 0o600 });

  console.log("=== BTC-Prometheus First Run ===");
  console.log(`Dashboard password: ${dashboardPassword}`);
  console.log("Save this password — you'll need it to log in to the dashboard.");
  console.log("You can also find it in Sovereign Controls after login.");
  console.log("================================");

  cached = creds;
  return creds;
}

// Dashboard auth exports
export function getCredentials(): DashboardCredentials {
  return ensureCredentials();
}

export function getDashboardPasswordHash(): string {
  return ensureCredentials().dashboardPasswordHash;
}

export function getDashboardPassword(): string {
  return ensureCredentials().dashboardPassword;
}

export function getJwtSecret(): string {
  return ensureCredentials().jwtSecret;
}

// First-run tracking — password is shown on screen until first login
export function isFirstRun(): boolean {
  return !ensureCredentials().claimed;
}

export function markClaimed(): void {
  const creds = ensureCredentials();
  creds.claimed = true;
  cached = creds;
  fs.writeFileSync(CRED_FILE, JSON.stringify(creds, null, 2), { mode: 0o600 });
}

// RPC cookie auth — read fresh every time (cookie changes on node restart)
export function getRpcCookieAuth(): string {
  return fs.readFileSync(COOKIE_FILE, "utf8").trim();
}
